apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sik-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sik-role
subjects:
- kind: ServiceAccount
  name: sik-sa
  namespace: sik-controller
