#!/bin/bash

echo 

echo "Setting up permission for controller ..."

kubectl apply -f ns.yml
kubectl apply -f serviceaccount.yml
kubectl apply -f role.yml
kubectl apply -f rolebinding.yml
kubectl apply -f deployment.yml
