apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sik-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sik-role
subjects:
- kind: ServiceAccount
  name: sik-serviceaccount
  namespace: sik-controller
